spring:
  application:
    name: SLLBackend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sll}
    username: ${DB_USER:sonbui}
    password: ${DB_PASS:sonbui}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 20000
      auto-commit: true
      pool-name: sonbui
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:triggers.sql
      separator: ^

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 25MB

image:
  upload:
    directory: ${IMAGE_UPLOAD_DIR:uploads/images}

server:
  port: 8080

vietqr:
  bank-id: ${VIETQR_BANK_ID:970407}
  account-no: ${VIETQR_ACCOUNT_NO:9720032001}
  template: ${VIETQR_TEMPLATE:qr_only}
